env:
  commonjs: true
  es2021: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
rules:
  indent:
    - error
    - tab
    
  linebreak-style:
    - error
    - windows

  quotes:
    - error
    - single

  semi:
    - error
    - never

  eqeqeq:
    - error
    - always

  no-console:
    - error

  no-unused-vars:
    - error

  comma-dangle: ["error", {
        "arrays": "never",
        "objects": "never",
        "imports": "never",
        "exports": "never",
        "functions": "never"
    }]

  comma-style: ["error", "last"]

  no-duplicate-imports:
    - error

  no-undefined:
    - error

  key-spacing:
    [error, { beforeColon: false, afterColon: true, mode: strict, align: value }]

  arrow-spacing: ["error", { "before": true, "after": true }]

  brace-style: ["error", "1tbs", { "allowSingleLine": true }]

  no-trailing-spaces: ["error", { "skipBlankLines": false,"ignoreComments": false }]

  eol-last: ["error", "never"]